### ISSUE TITLE
Problem of saving trained network parameters after network training

### ISSUE THREAD

**Issue by hanghoo** [IshitaTakeshi/PCANet#1]
Hello, if I want to save the network parameters, henceforth make test convenience, how can I do.

**Comment by IshitaTakeshi** [comment]
I think the easiest way is just saving the entire model :`pcanet` by pickle.
If you want to save only network parameters, trained parameters appear in `pcanet.pca_l1.components_` and `pcanet.pca_l2.components_`. So just save them with hyperparameters listed from [L141](https://github.com/IshitaTakeshi/PCANet/blob/master/pcanet.py#L141).
I have no idea about saving network parameters with HDF5 etc. since I'm not familiar with other deep learning frameworks, sorry.

**Comment by hanghoo** [comment]
@IshitaTakeshi Thank you very much.
