### ISSUE TITLE
Parameters of PCANet

### ISSUE THREAD

**Issue by damhurmuller** [IshitaTakeshi/PCANet#2]
Hello.

I can't understand the parameters of PCANet in relation of the original paper.

On the original paper the parameters for MNIST is set to 
PCANet.NumStages = 2;
PCANet.PatchSize = [7 7];
PCANet.NumFilters = [8 8];
PCANet.HistBlockSize = [7 7]; 
PCANet.BlkOverLapRatio = 0.5;
PCANet.Pyramid = [];

What are those parameters in the python code?
Sorry if is a dumb question.

I'm trying to put images of 224x224 (or something like that) but I need to understand the parameters to check if the structure is valid.

**Comment by IshitaTakeshi** [comment]
First of all, the number of stages is fixed to 2 in this implementation.

In that case, 

since MNIST contains images of shape (28, 28), 

```
image_shape=28
```

and patch sizes are 7 in both layers

```
filter_shape_l1 = filter_shape_l2 = 7
```
.

If you want 8 components from PCA (NumFilters) in both layers,

```
n_l1_output = n_l2_output = 8
```
.

`filter_shape_pooling` represents `HistBlockSize`

```
filter_shape_pooling = 7
```

but `step_shape_pooling` is unclear since it is half of the `HistBlockSize` which is 7.
Which one should it be? 3 or 4?

The original paper says 

```
block size is 7×7, and the overlapping region between blocks is half of the block size.
```

so it's unclear anyway.

__NOTE__: This implementation uses IncrementalPCA instead of the normal PCA since the normal one requires the whole dataset at the training time and consumes so much memory.

**Comment by damhurmuller** [comment]
Thanks for the explanation.
